### ISSUE TITLE
Create Pyodide web app

### ISSUE THREAD

**Issue by niemasd** [niemasd/GameID#3]
Right now, you need to run GameID from the command line. However, it's just a pure Python script, and its only current dependency is also pure Python. Thus, it would be great if there were an automatically-created web app that uses Pyodide to run GameID client-side in the browser. @daniel-ji is working on something

**Comment by niemasd** [comment]
@daniel-ji is a genius; web app is built! https://niema.net/GameID/

**Comment by daniel-ji** [comment]
😂 Definitely not a genius, thanks for the opportunity to build the site!
